image: registry.sensetime.com/sensego-sp/jenkins/inbound-agent:at1.2


deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:stable-dind
  script:
    - docker login registry.sensetime.com -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD
    - docker build -t registry.sensetime.com/cloudos/apitest:$CI_COMMIT_TAG .
    - docker push registry.sensetime.com/cloudos/apitest:$CI_COMMIT_TAG
  only:
    - tags
  except:
    - schedules
  tags:
    - docker

